version: '3.1'

networks:
  mysqlNet:
    name: mysqlNet
    driver: bridge

volumes:
  postgree-db:


services:
  mysql-db:
    image: mysql
    container_name: mysql
    restart: always
    networks:
      - mysqlNet
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_USER_PASSWORD: password
      MYSQL_DATABASE: mysqldb
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql